### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by dubima** [Libresonic/libresonic#264]
Ubuntu 14.04
Tomcat 7
OpenJDK 1.8/ Java 8

Hey guys,

I used to use subsonic (still have it installed but disabled) but stopped due to various open ports that i couldn't easily restrict to localhost only e.g 9412.

I have tomcat going for several other apps so i thought might as well use the .war file and do this setup quickly. Did the following after reading the INSTALL.md, though i got to ask what's the point of "/var/libresonic"?

Anyway:
```
service tomcat7 stop
mkdir /var/libresonic
wget https://jenkins.zifnab.net/job/libresonic/lastSuccessfulBuild/artifact/libresonic-main/target/libresonic.war -O /var/libresonic/libresonic.war
ln -s /var/libresonic/libresonic.war /var/lib/tomcat7/webapps/
chown -h tomcat7:tomcat7 /var/lib/tomcat7/webapps/libresonic.war
chown -R tomcat7:tomcat7 /var/libresonic
service tomcat7 start
```

Edit my apache config for a reverse proxy
hit https://url/libresonic but it's not working so i check catalina.out and it spews this (actual time and date replaced with words):
```
INFO: Deploying web application archive /var/lib/tomcat7/webapps/libresonic.war
[DATE TIME,577] ERROR org.springframework.web.context.ContextLoader - Context initialization failed
java.lang.UnsupportedClassVersionError: org/libresonic/player/spring/AdditionalPropertySourceConfigurer : Unsupported major.minor version 52.0 (unable to load class org.libresonic.player.spring.AdditionalPropertySourceConfigurer)
	at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2970)
	at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1209)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1689)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1570)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
	at org.springframework.web.context.ContextLoader.loadInitializerClass(ContextLoader.java:519)
	at org.springframework.web.context.ContextLoader.determineContextInitializerClasses(ContextLoader.java:509)
	at org.springframework.web.context.ContextLoader.customizeContext(ContextLoader.java:466)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5010)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5504)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1073)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
DATE TIME org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
DATE TIME org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/libresonic] startup failed due to previous errors
DATE TIME org.apache.catalina.startup.HostConfig deployDirectory
```
I also tried with https://github.com/Libresonic/libresonic/releases/download/v6.1/libresonic-v6.1.war but:
```
INFO: Deploying web application archive /var/lib/tomcat7/webapps/libresonic.war
[DATE TIME,523] WARN  org.springframework.beans.factory.support.DisposableBeanAdapter - Invocation of destroy method 'shutdown' failed on bean with name 'cxf': org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [org.libresonic.player.dao.PlayerDao] for bean with name 'playerDao' defined in ServletContext resource [/WEB-INF/applicationContext-service.xml]: problem with class file or dependent class; nested exception is java.lang.UnsupportedClassVersionError: org/libresonic/player/dao/PlayerDao : Unsupported major.minor version 52.0 (unable to load class org.libresonic.player.dao.PlayerDao)
[DATE TIME,529] ERROR org.springframework.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [org.libresonic.player.dao.PlayerDao] for bean with name 'playerDao' defined in ServletContext resource [/WEB-INF/applicationContext-service.xml]: problem with class file or dependent class; nested exception is java.lang.UnsupportedClassVersionError: org/libresonic/player/dao/PlayerDao : Unsupported major.minor version 52.0 (unable to load class org.libresonic.player.dao.PlayerDao)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1144)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:758)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:422)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:728)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:380)
	at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:255)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:199)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:45)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5010)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5504)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1073)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedClassVersionError: org/libresonic/player/dao/PlayerDao : Unsupported major.minor version 52.0 (unable to load class org.libresonic.player.dao.PlayerDao)
	at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2970)
	at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1209)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1689)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1570)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:211)
	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:385)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1138)
	... 22 more
DATE TIME org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
DATE TIME org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/libresonic] startup failed due to previous errors
DATE TIME org.apache.catalina.startup.HostConfig deployDirectory
```

I'm no java guy but I'm guessing the issue is with - "Unsupported major.minor version 52.0"?
Anyone else having problems, I'd be much happier rolling with the .war then building from source.
Any ideas?

**Comment by muff1nman** [comment]
You need to update your Java. There's a couple other issues that have been opened that are related so search some of the other issues to see if they can help.

**Comment by dubima** [comment]
```
:~$ java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-3~14.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
```

INSTALL.md
```
Prerequisites

In order to install and run Libresonic, you will need:

    A JDK installation. 1.8.x series of OpenJDK or Oracle JDK 8+ should work.
```

Am i missing something here?
Also is there like a discord server or something?

**Comment by muff1nman** [comment]
The java version for tomcat is not the same version that is set via `update-alternatives` or whatever the equivalent is for your distribution. I would look to set `JAVA_HOME` on your tomcat config.

**Comment by dubima** [comment]
Turned out there were some (2) symlinks that didn't want to update, did it manually and progressed further till another error. Checked here but apparently it should be fixed, both the springboard and database error?:
```
INFO: Deploying web application archive /var/lib/tomcat7/webapps/libresonic.war
[DATE TIME,927] WARN  org.springframework.web.context.support.XmlWebApplicationContext - Exception encountered during context initialization - canc$
[DATE TIME,940] ERROR org.springframework.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in ServletContext resource [/WEB-INF/applicationCo$
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1583)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:754)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5010)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5504)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1073)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: liquibase.exception.DatabaseException: java.sql.SQLException: The database is already in use by another process: org.hsqldb.persist.NIOLockFile@49$
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:393)
        at org.libresonic.player.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:24)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1642)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1579)
        ... 25 more
Caused by: java.sql.SQLException: The database is already in use by another process: org.hsqldb.persist.NIOLockFile@497ae66d[file =/db/libresonic.lck, exists$
        at org.hsqldb.jdbc.Util.sqlException(Unknown Source)
        at org.hsqldb.jdbc.jdbcConnection.<init>(Unknown Source)
        at org.hsqldb.jdbcDriver.getConnection(Unknown Source)
        at org.hsqldb.jdbcDriver.connect(Unknown Source)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)
        at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:153)
        at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:144)
        at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:196)
        at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:159)
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:388)
        ... 28 more
DATE TIME org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
DATE TIME org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/libresonic] startup failed due to previous errors
DATE TIME org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [/libresonic] registered the JDBC driver [org.hsqldb.jdbcDriver] but failed to unregister it when the web application was stopped$
DATE TIME org.apache.catalina.startup.HostConfig deployDirectory

```

**Comment by muff1nman** [comment]
`The database is already in use by another process` - make sure all other processes are shutdown. Looks like you still have something else using that db

**Comment by dubima** [comment]
rest of missing line
```
org.hsqldb.persist.NIOLockFile@497ae66d[file =/db/libresonic.lck, exists=false, locked=false, valid=false, fl =null]: java.io.FileNotFoundException: /db/libresonic.lck (No such file or directory)
```

Which database, I have several? mysql, couchdb, rethinkdb etc, all being used by other apps, even tomcat is using mysql right now. What's libre trying to do?

**Comment by muff1nman** [comment]
It's an hsql db. But reading that again, it's missing the libresonic home db directory. Make sure that directory is present. Are you changing the libresonic.home parameter?

**Comment by dubima** [comment]
made "/var/libresonic/db" but still same error.

**Comment by muff1nman** [comment]
It's trying to write to /db/libresonic.lck which seems to imply libresonic.home isnt being set correctly. You could try setting this value in your tomcat config

**Comment by dubima** [comment]
Ok but issue #198, you said you corrected the problem of not having libresonic.home defined in the java properties?

If i still have to do it then which config file is it best under and just "LIBRESONIC_HOME=/var/libresonic" or something else?

**Comment by dubima** [comment]
Turns out /var/libresonic is set/ is being used because after starting tomcat7 2 files appear in there:
libresonic.properties ( blank)
libresonic.log
```
[DATE TIME,445] ERROR SpringLiquibase - ===============================================
[DATE TIME,445] ERROR SpringLiquibase - An exception occurred during database migration
[DATE TIME,446] ERROR SpringLiquibase - A rollback file has been generated at /var/libresonic/rollback.sql
[DATE TIME,453] ERROR SpringLiquibase - Execute it within your database to rollback any changes
[DATE TIME,453] ERROR SpringLiquibase - The exception is as follows

liquibase.exception.DatabaseException: java.sql.SQLException: The database is already in use by another process: org.hsqldb.persist.NIOLockFile@497ae66d[file =/db/libresonic.lck, exists=false, locked=false, valid=false, fl =null]: java.io.FileNotFoundException: /db/libresonic.lck (No such file or directory)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:393)
	at org.libresonic.player.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:24)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1642)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1579)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:754)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5010)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5504)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1073)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: The database is already in use by another process: org.hsqldb.persist.NIOLockFile@497ae66d[file =/db/libresonic.lck, exists=false, locked=false, valid=false, fl =null]: java.io.FileNotFoundException: /db/libresonic.lck (No such file or directory)
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source)
	at org.hsqldb.jdbc.jdbcConnection.<init>(Unknown Source)
	at org.hsqldb.jdbcDriver.getConnection(Unknown Source)
	at org.hsqldb.jdbcDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:153)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:144)
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:196)
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:159)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:388)
	... 28 more

[DATE TIME,459] ERROR SpringLiquibase - ===============================================
```

Tomcat still spewing same error as before.

**Comment by muff1nman** [comment]
#198 only should not affect 6.1, which version are you using?

See #237 for an example on setting the parameter.

**Comment by dubima** [comment]
I'm assuming 6.1, downloaded from:
`https://jenkins.zifnab.net/job/libresonic/lastSuccessfulBuild/artifact/libresonic-main/target/libresonic.war`

Also setting up the file, for my environment, "/usr/share/tomcat7/bin/setenv.sh" with:
```
export JAVA_OPTS="$JAVA_OPTS -Dlibresonic.home=/var/libresonic"
```

has finally made it work, reversed proxy on and looking good, thanks for the help.
Questions though, should I or others really need to do this with the setenv?
Also what's up with all the db noise when starting tomcat up, looks like unnecessary schema, I mean some I don't even have music for? e.g
```
INFO DATE TIME: liquibase: classpath:liquibase/db-changelog.xml: classpath:liquibase/legacy/schema35.xml::schema35_010_Red-Hot-Chili-Peppers-1::muff1nmaff1nman: Prepared statement: INSERT INTO system_avatar(name, mime_type, width, height, data) VALUES(?, ?, ?, ?, ?)
```

**Comment by dubima** [comment]
I don't know if i should start a new issue and close this one or if this one is fine, let me know?

How come just like subsonic, libresonic also spawns use of port 45676? What's it used for, I can't find it when searching in the code, is it the callback service for url.libresonic.org or for DLNA/UPnP or Sonos or lastfm or?

Playing music works but playing videos doesn't with the following error
```
 Libresonic encountered an internal error. You can report this error in the Libresonic Forum. Please include the information below.
Exception 	org.apache.jasper.JasperException
Message 	/WEB-INF/jsp/videoPlayer.jsp (line: 67, column: 0) The end tag "</c:if" is unbalanced
Java version 	Oracle Corporation 1.8.0_111
Operating system 	Linux 4.4.0-64-generic
Server 	Apache Tomcat/7.0.52 (Ubuntu)
Memory 	Used 100 of 123 MB
Stack trace 	org.apache.jasper.JasperException: /WEB-INF/jsp/videoPlayer.jsp (line: 67, column: 0) The end tag "</c:if" is unbalanced
	at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:42)
	at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:443)
	at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:133)
	at org.apache.jasper.compiler.Parser.checkUnbalancedEndTag(Parser.java:1588)
	at org.apache.jasper.compiler.Parser.parseElements(Parser.java:1453)
	at org.apache.jasper.compiler.Parser.parse(Parser.java:138)
	at org.apache.jasper.compiler.ParserController.doParse(ParserController.java:242)
	at org.apache.jasper.compiler.ParserController.parse(ParserController.java:102)
	at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:198)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:373)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:353)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:340)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:657)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:357)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
	at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:168)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1257)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1037)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:980)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:146)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.libresonic.player.filter.RequestEncodingFilter.doFilter(RequestEncodingFilter.java:44)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.libresonic.player.filter.ParameterDecodingFilter.doFilter(ParameterDecodingFilter.java:55)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.libresonic.player.filter.BootstrapVerificationFilter.doFilter(BootstrapVerificationFilter.java:60)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:315)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by muff1nman** [comment]
Well there you go, you're actually running 6.2 as you have liquibase managing your database now. I don't know how recent that build is though so it could be impacted by #198. For future reference you should pull binaries from GitHub unless you want something newer. 

Please open a new issue for your other questions. Though it might be good to get a more recent build before doing so.

**Comment by muff1nman** [comment]
In fact I'd be interested in seeing what your about page says.

**Comment by dubima** [comment]
I'm guessing this is what you wanted
```
About Libresonic
Version	6.2.beta1 – December 30, 2016
Server	Apache Tomcat/7.0.52 (Ubuntu), java 1.8.0_111, Linux (79.9 MB / 123.8 MB)
```

Also the above error is only for 6.2.beta1. I've changed to 6.1 and working so will close this and open another issue. If you want anything else let me know, I still have it, probably not for too long though.

**Comment by muff1nman** [comment]
Yeah, so that is an old 6.2 build. We only want to new issues for stable or the latest develop branch.
